spring.jpa.hibernate.ddl-auto: update

#db url im fenster console: jdbc:h2:mem:chatdb
spring:
  datasource:
    url: jdbc:h2:mem:chatdb
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 941832897112-4h5r9fscdpjelp03ko0sd7au6dtsnktb.apps.googleusercontent.com
            client-secret: EpKCdUEtksjbLmttoRMiNc6C

spring.h2.console.enabled: true
#url der console im browser
spring.h2.console.path: /h2-console/

server.servlet.session.timeout: 30s

google.recaptcha.key.site: 6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI
google.recaptcha.key.secret: 6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe

